config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'photo/index'

  get 'photos/index'
  get 'users/index'
  get 'friends/index'

  root 'photos#index'

  resources :photos
  resources :users
  resources :friends

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

        can :read, [Photo, Friend, User]
        can :create, [Photo, Friend, User]
 
        can [:update, :destroy], Photo do |photo|
            photo.user_id == user.id
            # Add Comments later
        end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/friend.rb
class Friend < ActiveRecord::Base

  belongs_to :self, :class_name => 'User', :foreign_key => 'self_id'
  belongs_to :friend, :class_name => 'User', :foreign_key => 'friend_id'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, PhotoImageUploader

  belongs_to :user
  has_many :comments
  has_many :likes

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, UserAvatarUploader

  #validates :friendslist, uniqueness: true

  has_many :friendships, :class_name => 'Friend', :foreign_key => 'self_id'
  has_many :inverse_friendships, :class_name => 'Friend', :foreign_key => 'friend_id'
  has_many :photos
  has_many :comments
  has_many :messages

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def role?(role_to_compare)
    self.role.to_s = role_to_compare.to_s
  end

  def friendslist(id)
    # Find friendships where self_id = user.id
    @friends = self.friendships(self_id = id)
    # Find friendships where friend_id = user.id
    @inverse_friends = self.inverse_friendships(friend_id = id)
    # @all_friends =  concatenate @friends @inverse_friends
    @all_friends = [@friends, @inverse_friends].flatten
    return @all_friends
  end

  def display_name(current_user,friend)
    # current user id (logged in person)
    # compare with the friend_id and self_id
    # whichever it matches, take the opposite
    result = ""
    compare_id = current_user.id
    same_as_friend = compare_id == friend.id
    same_as_self = compare_id == id
    # VAL IS GOD
    if(same_as_self)
      result = friend.name
    else
      result = name
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @photos = Photo.all
    @users = User.order(name: :asc)

    friends = current_user.friendslist(current_user.id)

    @sorted = friends.sort_by {|f| f.self.display_name(current_user, f.friend) }
    
    # @friends = Friend.where('friend_id=? OR self_id=?', current_user.id, current_user.id)
  end

  def create
    @friendship = Friend.new
    @friendship.friend_id = params[:friend_id]
    @friendship.self_id = current_user.id
    @friendship.save
    redirect_to(friends_index_path)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @photos = Photo.all
    @users = User.all
  end

  def new
    @photo = Photo.new
  end

  def create
    current_user.photos.create(photo_params)
    redirect_to(photos_index_path)
  end

  def show
    @photo = Photo.find(params[:id])
    @users = User.all
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    photo = Photo.find(params[:id])
    photo.update(photo_params)
    redirect_to(photos_path)
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy
    redirect_to(photos_path)
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :image, :description, :user_id)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :job, :location)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :job, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @friends = current_user.friendslist(current_user.id)
    #@users = User.all
    # @users = User.order(name: :asc)
    @other_users = get_other_users
  end

  def get_other_users
    # id = current_user.id
    # @users = User.find_by_sql("SELECT * FROM users WHERE users.id != ?", id)
    @users = User.where.not(id: current_user.id).order(name: :asc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/friends/index.html.erb
<h1>Friends</h1>
<p>
  <% @sorted.each do |f| %>
  <div class="grid grid-4">
    <ul>
      <!-- VAL MADE FUN OF ME -->
      <% if f.friend_id == current_user.id %>
      <li><%= image_tag(@users.find(f.self_id).avatar.page.url, alt: 'No Image') %></li>
      <br>
      <li><%= @users.find(f.self_id).name %></li>
      <br>
      <li>Job: <%= @users.find(f.self_id).job %></li>
      <br>
      <li>Location: <%= @users.find(f.self_id).location %></li>

      <% else %>

      <li><%= image_tag(@users.find(f.friend_id).avatar.page, alt: 'No Image') %></li>
      <br>
      <li><%= @users.find(f.friend_id).name %></li>
      <br>
      <li>Job: <%= @users.find(f.friend_id).job %></li>
      <br>
      <li>Location: <%= @users.find(f.friend_id).location %></li>
      <% end %>

    </ul>

  </div>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project1</title>
  <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
  <% if current_user %>
  <%= image_tag(current_user.avatar.thumb) %>
    <div class="go-left">
      <div class="logo">
        <ul>
          <% if current_user %>
         <!--  <li><%= image_tag(current_user.avatar.thumb) %></li> -->
          <li><%= "Hi #{current_user.name}!" %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Your Details', edit_user_registration_path %></li>
          <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Register', new_user_registration_path %></li>
          <% end %>
        </div>
      </div>
      <% end %>

      <div class="go-right">
        <ul>
          <li> <%= link_to 'View All Users', users_index_path %></li>
          <li> <%= link_to 'See Your Friends', friends_index_path %></li>
          <li> <%= link_to 'View All Photos', photos_index_path %> </li>
          <li> <%= link_to 'Add New Photo', new_photo_path %> </li>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <main class="container">
      <%= yield %>
    </main>

  </body>
  </html>

app/views/photos/edit.html.erb
<h1>Edit Your Photo Details</h1>

<%= form_for @photo do |f| %>
<%= f.label :title, 'Photo Title: ' %>
<%= f.text_field :title %>
<br>
<br>

<%= f.label :description, 'Enter a Description: ' %>
<br>
<%= f.text_area :description %>
<br>
<br>

Click the button below to edit your photo details!
<br>
<%= f.submit 'Edit Photo Details!' %>

<% end %>

app/views/photos/index.html.erb
<h1>Photos</h1>
<p>
  <% @photos.each do |photo| %>
  <div class="grid grid-4">
    <ul>
      <li><%= link_to image_tag(photo.image.thumb.url, alt: 'No Image'), photo_path(photo) %></li>
      <br>
      <li>Title: <%= photo.title %></li>
      <br>
      <li>Description: <%= photo.description if photo.description %></li>
    </ul>

    <% if can? :update, photo %>
    <%= link_to("Edit Your Photo Details", edit_photo_path(photo)) %>
    <% else %>
    This is <%= @users.find(photo.user_id).name %>'s photo.
    &emsp;&emsp;&emsp;&emsp;
    <%= image_tag(@users.find(photo.user_id).avatar.thumb.url) %>
    <% end %>

    <br>

    <% if can? :destroy, photo %>
    <%= link_to("Delete Your Photo", photo_path(photo), method: :delete, data: {confirm: "Do you really want to delete this photo?"}) %>
    <% end %>
    <br>
    <br>
  </div>
  <% end %>
</p>

app/views/photos/new.html.erb
<h1>Add a New Photo</h1>

<%= form_for @photo do |f| %>
<%= f.label :title, 'Photo Title: ' %>
<%= f.text_field :title %>
<br>
<br>

<%= f.label :image, 'Click this button, then choose the photo you wish to upload.' %>
<br>
<%= f.file_field :image %>
<br>
<br>

<%= f.label :description, 'Enter a Description: ' %>
<br>
<%= f.text_area :description %>
<br>
<br>

Click the button below to add your photo!
<br>
<%= f.submit 'Add New Photo!' %>

<% end %>

app/views/photos/show.html.erb
<ul>
    <li>Photo Title: <%= @photo.title %>
      <br>
      <br>
      <%= image_tag(@photo.image.medium, alt: 'No Image') %>
      <br>
      <br>

      Description:
      <br>
      <br>
      <%= @photo.description if @photo.description %></li>
    </ul>

    <% if can? :update, @photo %>
    <%= link_to("Edit Your Photo Details", edit_photo_path(@photo)) %>
    <% else %>
    This is <%= @users.find(@photo.user_id).name %>'s photo.
    <%= image_tag(@users.find(@photo.user_id).avatar.thumb.url) %>
    <% end %>

    <br>

    <% if can? :destroy, @photo %>
    <%= link_to("Delete Your Photo", photo_path(@photo), method: :delete, data: {confirm: "Do you really want to delete this photo?"}) %>
    <% end %>

    <br>
    <hr>
  </p>

app/views/users/index.html.erb
<h1>List of Users</h1>
<p>

  <% @users.each do |u| %>
  <div class="grid grid-4">
    <ul>
      <% unless u.id == current_user.id %>

      <li><%= image_tag(u.avatar.thumb.url, alt: 'No Image', class: "friend_avatar") %></li>
      <br>
      <li><%= u.name %></li>
      <br>
      <li>Job: <%= u.job %></li>
      <br>
      <li>Location: <%= u.location %></li>
      <br>

      <% if @friends.any?{|f| f.self_id == u.id || f.friend_id == u.id} %>
      <!-- Thanks Beth! -->
      <li>You and <%= u.name %> are already friends.</li>
      <br>

      <% else %>

      <li><%= link_to("Add #{u.name} as a friend!", friends_path(friend_id: u.id), :method => :post) %></li>

      <% end %>
      <% end %>
    </ul>
  </div>
  
  <% end %>

  <section class="row">
  </section>

</p>